version: '3.8'
services:
  cloud-native-app:
    image: cloud-native-app:v1
    build: .   # 支持直接从Dockerfile构建
    ports:
      - "8080:8080"
    volumes:
      - app-logs:/logs
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 3s
      retries: 3

volumes:
  app-logs: